name: Format
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [master]
jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            actions: write
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT }}
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
            - run: npm ci
            - run: npm run format
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
    lint:
        needs: format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
            - run: npm ci
            - run: npm run lint
